/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt1;

import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author minna
 */
public class Inloggning extends javax.swing.JFrame {

        private InfDB idb;
    /**
     * Creates new form Inloggning
     */
        
    public Inloggning(InfDB idb) {
        this.idb=idb;
        initComponents();
        lblFelMeddelande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEPost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        tfeEpost = new javax.swing.JTextField();
        tfLosenord = new javax.swing.JTextField();
        lblFelMeddelande = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEPost.setText("Epost");

        lblLosenord.setText("Lösenord");

        tfeEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfeEpostActionPerformed(evt);
            }
        });

        tfLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLosenordActionPerformed(evt);
            }
        });

        lblFelMeddelande.setForeground(new java.awt.Color(255, 0, 0));
        lblFelMeddelande.setText("Felaktig Epost eller Lösenord");

        btnLoggaIn.setForeground(new java.awt.Color(102, 153, 255));
        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        jLabel1.setText("Välkommen Användare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnLoggaIn)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEPost, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLosenord)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfeEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(tfLosenord))))
                    .addComponent(lblFelMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEPost)
                    .addComponent(tfeEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(tfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFelMeddelande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoggaIn)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLosenordActionPerformed

    private void tfeEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfeEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfeEpostActionPerformed

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        //Skapar inloggning och kontrollerar att användaren finns i databasen
        String ePost = tfeEpost.getText();
        String lösen=tfLosenord.getText();
        
    
    try {
        // Hämtar lösenordet från databasen
        String sqlFråga = "SELECT losenord FROM anstalld WHERE epost = '" + ePost + "'";
        String dbLosen = idb.fetchSingle(sqlFråga);

        // Kontrollera om lösenordet är korrekt
        if (dbLosen == null || !lösen.equals(dbLosen)) {
            lblFelMeddelande.setVisible(true);
            return; // Avbryt inloggningen om lösenordet inte stämmer
        }

        // Om lösenordet är korrekt, fortsätt med att kontrollera användarroll
        // Kontrollera om användaren är en handläggare
        String sqlHandlaggare = "SELECT anstalld.aid FROM anstalld JOIN handlaggare ON anstalld.aid = handlaggare.aid WHERE epost = '" + ePost + "'";
        String dbAid = idb.fetchSingle(sqlHandlaggare);
        if (dbAid != null) {
            MenyHandlaggare meny = new MenyHandlaggare(idb, dbAid);
            meny.setVisible(true);
            this.setVisible(false);
            return;
        }

        // Kontrollera om användaren är en administratör
        String sqlAdmin = "SELECT anstalld.aid FROM anstalld JOIN admin ON anstalld.aid = admin.aid WHERE epost = '" + ePost + "'";
        dbAid = idb.fetchSingle(sqlAdmin);
        if (dbAid != null) {
            MenyAdministratör meny = new MenyAdministratör(idb, dbAid);
            meny.setVisible(true);
            this.setVisible(false);
            return;
        }

        // Kontrollera om användaren är en projektledare
        String sqlProjektChef = "SELECT projekt.projektchef FROM projekt JOIN anstalld ON projekt.projektchef = anstalld.aid WHERE epost = '" + ePost + "'";
        dbAid = idb.fetchSingle(sqlProjektChef);
        if (dbAid != null) {
            MenyProjektLedare meny = new MenyProjektLedare(idb, dbAid);
            meny.setVisible(true);
            this.setVisible(false);
            return;
        }

        // Om användaren inte tillhör någon av ovanstående roller
        lblFelMeddelande.setVisible(true);

    } catch (InfException ex) {
        System.out.println("Fel vid inloggning: " + ex.getMessage());
    }


    }//GEN-LAST:event_btnLoggaInActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEPost;
    private javax.swing.JLabel lblFelMeddelande;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JTextField tfLosenord;
    private javax.swing.JTextField tfeEpost;
    // End of variables declaration//GEN-END:variables
}
