/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt1;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author elsa
 */
public class MenyAndraProjektetsDataProjektledare extends javax.swing.JFrame {
        private InfDB idb;
        private String dbAid;


    public MenyAndraProjektetsDataProjektledare(InfDB idb, String dbAid) {
            this.idb = idb; 
            this.dbAid = dbAid;
            initComponents();
            
            fyllProjektledarensProjektComboBox();
            
            fyllProjektetsTabell();
        

        
    }
    
    // Fyller ComboBox med alla projektnamn för projekt som tillhör projektchefen
    public void fyllProjektledarensProjektComboBox() {
        try {
            String sqlFraga = "SELECT projektnamn FROM projekt WHERE pid = " + dbAid;
           
            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);
            
            
            ProjektledarensProjekt.removeAllItems();
            
            // Lägger till projektnamnen i ComboBox
            if (resultat != null && !resultat.isEmpty()) {
                for (HashMap<String, String> rad : resultat) {
                    ProjektledarensProjekt.addItem(rad.get("projektnamn"));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Inga projekt hittades för projektledaren.");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av projektlistan: " + e.getMessage());
        }
    }

    // Fyller tabellen med all data om projektet som projektchefen är chef över
    public void fyllProjektetsTabell() {
    try {
        // SQL-fråga för att hämta all projektdata 
        String sqlFraga = "SELECT DISTINCT projektnamn, beskrivning, status, prioritet, startdatum, slutdatum, kostnad " +
                "FROM projekt WHERE pid = " + dbAid;
       
        ArrayList<HashMap<String, String>> resultat = idb.fetchRows(sqlFraga);


        DefaultTableModel model = (DefaultTableModel) tblProjektetsData.getModel();
        model.setRowCount(0);

       if (resultat !=null){
           
        // Lägger till all data om projekt i tabellen
        for (HashMap<String, String> rad : resultat) {
            model.addRow(new Object[] { 
                rad.get("projektnamn"), 
                rad.get("beskrivning"), 
                rad.get("status"),
                rad.get("prioritet"),
                rad.get("startdatum"),
                rad.get("slutdatum"), 
                rad.get("kostnad"), 
 
            });
        }
        }

    } catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av projektets data: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProjektetsData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjektetsData = new javax.swing.JTable();
        btnSparaAndringar = new javax.swing.JButton();
        tfdNyttProjektnamn = new javax.swing.JTextField();
        tfdAngeNyBeskrivning = new javax.swing.JTextField();
        tfdAngeNyStatus = new javax.swing.JTextField();
        tfdAngeNyPrioritet = new javax.swing.JTextField();
        tfdNyttStartDatum = new javax.swing.JTextField();
        tfdNyttSlutDatum = new javax.swing.JTextField();
        tfdAngeNyKostnad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ProjektledarensProjekt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblProjektetsData.setText("Dina Projekts data:");

        tblProjektetsData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Projektnamn", "Beskrivning", "Status", "Prioritet", "Start datum", "Slut datum", "Kostnad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProjektetsData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProjektetsDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProjektetsData);

        btnSparaAndringar.setText("Spara ny data");
        btnSparaAndringar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSparaAndringarMouseClicked(evt);
            }
        });

        tfdNyttProjektnamn.setText("Ange nytt Projektnamn");

        tfdAngeNyBeskrivning.setText("Ange ny beskrivning");
        tfdAngeNyBeskrivning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdAngeNyBeskrivningActionPerformed(evt);
            }
        });

        tfdAngeNyStatus.setText("Ange ny status");

        tfdAngeNyPrioritet.setText("Ange ny prioritet");

        tfdNyttStartDatum.setText("Ange nytt Start datum");

        tfdNyttSlutDatum.setText("Ange nytt Slut datum");

        tfdAngeNyKostnad.setText("Ange ny kostnad");

        jLabel1.setText("Välj Projekt att ändra: ");

        ProjektledarensProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSparaAndringar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tfdNyttSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdNyttStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProjektledarensProjekt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdAngeNyPrioritet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdAngeNyStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfdAngeNyBeskrivning)
                                .addComponent(tfdNyttProjektnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))))
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProjektetsData))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(tfdAngeNyKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblProjektetsData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNyttProjektnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdAngeNyBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjektledarensProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tfdAngeNyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdAngeNyPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfdNyttStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdNyttSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdAngeNyKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSparaAndringar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metod som sparar ändringar av projektets data
    private void btnSparaAndringarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSparaAndringarMouseClicked
           

        
        String nyttProjektnamn = tfdNyttProjektnamn.getText();
        String nyttBeskrivning = tfdAngeNyBeskrivning.getText();
        String nyttStatus = tfdAngeNyStatus.getText();
        String nyttPrioritet = tfdAngeNyPrioritet.getText();
        String nyttStartdatum = tfdNyttStartDatum.getText();
        String nyttSlutdatum = tfdNyttSlutDatum.getText();
        String nyttKostnad = tfdAngeNyKostnad.getText();
        
                  //Uppdetara de sparade ändringar i databasen
        
                 if (!Validering.isValidNamn(nyttStatus)|| !Validering.isValidNamn(nyttPrioritet)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ogiltig Status! Endast bokstäver och minst två tecken långt är tillåtna.");
            return;
        }
        if (!Validering.isValidDatum(nyttStartdatum) || !Validering.isValidDatum(nyttSlutdatum)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ogiltigt datum! Kontrollera att månad och dag är korrekta, till exempel 2023-02-29 är endast tillåtet under skottår.!");
            return;
         }
        if (!Validering.isNumerisk(nyttKostnad)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ogiltig inmatning! Endast siffror och eventuellt en decimalpunkt är tillåtna.");
            return;
        }
        if (!Validering.isValidAdress(nyttProjektnamn)) {
            javax.swing.JOptionPane.showMessageDialog(this, "projektnamn får inte vara tom, Vänligen fyll i ex projekt 2.");
            return;
        }
        if (!Validering.isValidLongText(nyttBeskrivning)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Beskrivning får ej vara tomt, avsluta med en punkt.");
            return;
        }
        
        try {
        //Uppdaterar tabellen med de sparade ändringarna
        String uppdatering = "UPDATE projekt SET " +  
        "projektnamn = '" + nyttProjektnamn + "', " + 
        "beskrivning = '" + nyttBeskrivning + "', " +
        "startdatum = '" + nyttStartdatum + "', " + 
        "slutdatum = '" + nyttSlutdatum + "', " + 
        "kostnad = '" + nyttKostnad + "', " + 
        "status = '" + nyttStatus + "', " + 
        "prioritet = '" + nyttPrioritet + "' " + 
        "WHERE pid = " + dbAid;
            
        System.out.println(uppdatering);

            idb.update(uppdatering);
            
            //Visar meddelande om att projektets ändringar ärsparade
            JOptionPane.showMessageDialog(this, "Dina projektändringar är sparade!");
            
            fyllProjektledarensProjektComboBox();
            fyllProjektetsTabell();
        } catch (Exception e) {
            // Meddelande om att inmatade ändringar är gjorda på fel sätt
            JOptionPane.showMessageDialog (this, "Fel vid inmatning av ändringar!" + e.getMessage());
        }   


    }//GEN-LAST:event_btnSparaAndringarMouseClicked

    private void tfdAngeNyBeskrivningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdAngeNyBeskrivningActionPerformed

    }//GEN-LAST:event_tfdAngeNyBeskrivningActionPerformed

        //Metod som gör att man kan trycka i tabellen för att kunna ändra datan
    private void tblProjektetsDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProjektetsDataMouseClicked
        

        int rad = tblProjektetsData.getSelectedRow();
        if (rad != -1) {
            String projektnamn = (String) tblProjektetsData.getValueAt(rad, 0);
            String beskrivning = (String) tblProjektetsData.getValueAt(rad, 1);
            String status = (String) tblProjektetsData.getValueAt(rad, 2);
           String prioritet = (String) tblProjektetsData.getValueAt(rad, 3);
            String startdatum = (String) tblProjektetsData.getValueAt(rad, 4);
            String slutdatum = (String) tblProjektetsData.getValueAt(rad, 5);
            String kostnad = (String) tblProjektetsData.getValueAt(rad, 6);

            tfdNyttProjektnamn.setText(projektnamn);
            tfdAngeNyBeskrivning.setText(beskrivning);
            tfdAngeNyStatus.setText(status);
            tfdAngeNyPrioritet.setText(prioritet);
            tfdNyttStartDatum.setText(startdatum);
            tfdNyttSlutDatum.setText(slutdatum);
            tfdAngeNyKostnad.setText(kostnad);
          }

    }//GEN-LAST:event_tblProjektetsDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyAndraProjektetsDataProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyAndraProjektetsDataProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyAndraProjektetsDataProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyAndraProjektetsDataProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenyAndraProjektetsDataProjektledare().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ProjektledarensProjekt;
    private javax.swing.JButton btnSparaAndringar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProjektetsData;
    private javax.swing.JTable tblProjektetsData;
    private javax.swing.JTextField tfdAngeNyBeskrivning;
    private javax.swing.JTextField tfdAngeNyKostnad;
    private javax.swing.JTextField tfdAngeNyPrioritet;
    private javax.swing.JTextField tfdAngeNyStatus;
    private javax.swing.JTextField tfdNyttProjektnamn;
    private javax.swing.JTextField tfdNyttSlutDatum;
    private javax.swing.JTextField tfdNyttStartDatum;
    // End of variables declaration//GEN-END:variables
}
