/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt1;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author elsa
 */
public class MenyAndraHandlaggareProjektProjektledare extends javax.swing.JFrame {
        private InfDB idb;
        private String dbAid;

    /**
     * Creates new form MenyAndraHandlaggareProjektProjektledare
     */
    public MenyAndraHandlaggareProjektProjektledare(InfDB idb, String dbAid) {
            this.idb = idb; 
            this.dbAid = dbAid;
            initComponents();
            
            
            fyllProjektetshandlaggare();
            
    }
    public void fyllProjektetshandlaggare () {
        
        try {
            
            String sqlFraga = "SELECT anstalld.fornamn, anstalld.efternamn, handlaggare.ansvarighetsomrade " +
                        "FROM anstalld " +
                        "JOIN handlaggare ON anstalld.aid = handlaggare.aid " +
                        "JOIN ans_proj ON anstalld.aid = ans_proj.aid " +
                        "JOIN projekt ON ans_proj.pid = projekt.pid " +
                        "WHERE projektchef = " + dbAid;
            
            ArrayList<HashMap<String, String>> resultatx = idb.fetchRows(sqlFraga);
            
            if (resultatx == null || resultatx.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Inga handläggare för projektet hittades." );
            }
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Handlaggare");
            model.addColumn("Ansvarighetsomrade");
            
            for (HashMap<String, String> rad : resultatx) {
                model.addRow(new Object[]{rad.get("fornamn"), rad.get("ansvarighetsomrade")});
                
            }
            
            tblProjektetshandlaggare.setModel(model);
            
        } catch (InfException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Fel vid hämtning av projektets handläggare: " + e.getMessage());
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdAngeHandlaggare = new javax.swing.JTextField();
        btnLaggTillHandlaggare = new javax.swing.JButton();
        tfdTaBortHandlaggare = new javax.swing.JTextField();
        btnTaBortHandlaggare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjektetshandlaggare = new javax.swing.JTable();
        lblProjektetsHandlaggare = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfdAngeHandlaggare.setText("Ange Handläggare");

        btnLaggTillHandlaggare.setText("Lägg till Handläggare");
        btnLaggTillHandlaggare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaggTillHandlaggareMouseClicked(evt);
            }
        });
        btnLaggTillHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillHandlaggareActionPerformed(evt);
            }
        });

        tfdTaBortHandlaggare.setText("Ange Handlaggare");

        btnTaBortHandlaggare.setText("Ta bort Handläggare");
        btnTaBortHandlaggare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaBortHandlaggareMouseClicked(evt);
            }
        });

        tblProjektetshandlaggare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Handlaggare"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProjektetshandlaggare);

        lblProjektetsHandlaggare.setText("Projektets Handläggare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProjektetsHandlaggare)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfdAngeHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(tfdTaBortHandlaggare))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnLaggTillHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTaBortHandlaggare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblProjektetsHandlaggare)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdAngeHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaggTillHandlaggare))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdTaBortHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaBortHandlaggare))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillHandlaggareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaggTillHandlaggareActionPerformed

    private void btnLaggTillHandlaggareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaggTillHandlaggareMouseClicked
        // TODO add your handling code here:
            // Hämta text från fältet
    String handlaggareNamn = tfdAngeHandlaggare.getText().trim();

    // Kontrollera att fältet inte är tomt
    if (handlaggareNamn.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fyll i handläggarens namn.", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Lägg till handläggaren i tabellen
    DefaultTableModel model = (DefaultTableModel) tblProjektetshandlaggare.getModel();
    model.addRow(new Object[]{handlaggareNamn});

    // Rensa textfältet
    tfdAngeHandlaggare.setText("");

    }//GEN-LAST:event_btnLaggTillHandlaggareMouseClicked

    private void btnTaBortHandlaggareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaBortHandlaggareMouseClicked
        // TODO add your handling code here:

    // Hämta text från fältet
    String handlaggareNamn = tfdTaBortHandlaggare.getText().trim();

    // Kontrollera att fältet inte är tomt
    if (handlaggareNamn.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Fyll i handläggarens namn.", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Ta bort handläggaren från tabellen
    DefaultTableModel model = (DefaultTableModel) tblProjektetshandlaggare.getModel();
    boolean found = false;

    for (int i = 0; i < model.getRowCount(); i++) {
        String currentHandlaggare = model.getValueAt(i, 0).toString();
        if (currentHandlaggare.equalsIgnoreCase(handlaggareNamn)) {
            model.removeRow(i);
            found = true;
            break;
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(null, "Handläggaren hittades inte i tabellen.", "Fel", JOptionPane.ERROR_MESSAGE);
    }

    // Rensa textfältet
    tfdTaBortHandlaggare.setText("");

    }//GEN-LAST:event_btnTaBortHandlaggareMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyAndraHandlaggareProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyAndraHandlaggareProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyAndraHandlaggareProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyAndraHandlaggareProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenyAndraHandlaggareProjektProjektledare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillHandlaggare;
    private javax.swing.JButton btnTaBortHandlaggare;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblProjektetsHandlaggare;
    private javax.swing.JTable tblProjektetshandlaggare;
    private javax.swing.JTextField tfdAngeHandlaggare;
    private javax.swing.JTextField tfdTaBortHandlaggare;
    // End of variables declaration//GEN-END:variables
}
