package projekt1;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author cecil
 */
public class MenyHallbarhetsmalHandlaggare extends javax.swing.JFrame{
    private InfDB idb; 
    private String dbAid;

    /**
     * Creates new form MenyHallbarhetsmalHandlaggare
     */
    public MenyHallbarhetsmalHandlaggare(InfDB idb, String dbAid) {
        this.idb = idb; 
        this.dbAid = dbAid; 
        initComponents();
        fyllComboBox(); //fyller rullistan med data från databasen
        
        //lägg till en lyssnare för att hantera val från rullistan
        jComboBox1.addActionListener(evt -> {
        String valtMål = (String) jComboBox1.getSelectedItem();//hämta valt namn
        System.out.println("Användaren valde: " + valtMål);

       });
        
    }
    
    private void fyllComboBox() {
        try{
            String query ="SELECT namn FROM hallbarhetsmal";
            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(query);
            
            if (resultat !=null) {
                jComboBox1.removeAllItems();
                for (HashMap <String, String> rad : resultat) {
                 jComboBox1.addItem(rad.get("namn"));
                }
            }else{
                JOptionPane.showMessageDialog(this, "Inga hållbarhetsmål hittades i databasen.");

            }               
            } catch (InfException e) {
                JOptionPane.showMessageDialog(this, "Fel vid hämtning av hållbarhetsmål.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHallbarhetsmal = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHallbarhetsmal.setText("Alla Hållbarhetsmål");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHallbarhetsmal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHallbarhetsmal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    

 public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                InfDB idb = new InfDB("databasensSökväg");
                new MenyHallbarhetsmalHandlaggare(idb, "1").setVisible(true);
            } catch (InfException e) {
                System.out.println("Fel vid anslutning till databasen: " + e.getMessage());
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblHallbarhetsmal;
    // End of variables declaration//GEN-END:variables

}
