/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekt1;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author elsa
 */
public class MenyUppgifterOmProjektProjektledare extends javax.swing.JFrame {
      private InfDB idb;
    private String dbAid;

    /**
     * Creates new form MenyUppgifterOmProjektProjektledare
     */
    public MenyUppgifterOmProjektProjektledare(InfDB idb, String dbAid) {
        this.idb = idb;
        this.dbAid = dbAid;
        initComponents();
        
        FylliTextfalt();
    }
    
    private void FylliTextfalt () {
        try { 
            String sqlFraga = "SELECT projektnamn, kostnad, beskrivning, startdatum, slutdatum, status, prioritet, projektchef, land " +
            "FROM projekt " +
            "WHERE projektchef = " + dbAid;
            
            HashMap <String, String> userData = idb.fetchRow(sqlFraga);
            
            if(userData !=null) {
                tfdProjektNamn.setText(userData.get("projektnamn"));
                tfdKostnad.setText(userData.get("kostnad"));
                tfdBeskrivning.setText(userData.get("beskrivning"));
                tfdStartDatum.setText(userData.get("startdatum"));
                tfdSlutDatum.setText(userData.get("slutdatum"));
                tfdStatus.setText(userData.get("status"));
                tfdPrioritet.setText(userData.get("prioritet"));
                
            }else{ JOptionPane.showMessageDialog(this, "Ingen data om projekt på avdelning hittades!");
            
            }
        }catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av data!");
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKostnader = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        tfdKostnad = new javax.swing.JTextField();
        tfdStatus = new javax.swing.JTextField();
        lblPartnersForProjekt = new javax.swing.JLabel();
        tfdAndraPartners = new javax.swing.JTextField();
        lblHandlaggareforProjekt = new javax.swing.JLabel();
        lblAndraHandlaggare = new javax.swing.JTextField();
        lblUppgifterOmProjekt = new javax.swing.JLabel();
        lblProjektNamn = new javax.swing.JLabel();
        lblProjektbeskrivning = new javax.swing.JLabel();
        lblStartDatum = new javax.swing.JLabel();
        lblSlutDatum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLand = new javax.swing.JLabel();
        tfdProjektNamn = new javax.swing.JTextField();
        tfdBeskrivning = new javax.swing.JTextField();
        tfdStartDatum = new javax.swing.JTextField();
        tfdSlutDatum = new javax.swing.JTextField();
        tfdPrioritet = new javax.swing.JTextField();
        btnSparaAndringar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKostnader.setText("Kostnader");

        lblStatus.setText("Status");

        tfdKostnad.setText("Kostnader");
        tfdKostnad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdKostnadActionPerformed(evt);
            }
        });

        tfdStatus.setText("Status");
        tfdStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdStatusActionPerformed(evt);
            }
        });

        lblPartnersForProjekt.setText("Partners för projekt: ");

        tfdAndraPartners.setText("Lägg till eller ta bort Partners");
        tfdAndraPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdAndraPartnersActionPerformed(evt);
            }
        });

        lblHandlaggareforProjekt.setText("Handläggare för projekt:");

        lblAndraHandlaggare.setText("Lägg till eller ta bort Handläggare");
        lblAndraHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAndraHandlaggareActionPerformed(evt);
            }
        });

        lblUppgifterOmProjekt.setText("Uppgifter om projekt på avdelning");

        lblProjektNamn.setText("Projekt namn");

        lblProjektbeskrivning.setText("Beskrivning");

        lblStartDatum.setText("Start datum");

        lblSlutDatum.setText("Slut datum");

        jLabel1.setText("Prioritet");

        lblLand.setText("Land");

        tfdProjektNamn.setText("projektnamn");

        tfdBeskrivning.setText("Beskrivning");

        tfdStartDatum.setText("Start datum");

        tfdSlutDatum.setText("Slut datum");

        tfdPrioritet.setText("Prioritet");

        btnSparaAndringar.setText("Spara ändringar");
        btnSparaAndringar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSparaAndringarMouseClicked(evt);
            }
        });
        btnSparaAndringar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaAndringarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKostnader, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblUppgifterOmProjekt))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSlutDatum)
                        .addGap(163, 163, 163)
                        .addComponent(lblHandlaggareforProjekt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAndraHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProjektbeskrivning))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStartDatum))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfdProjektNamn)
                                    .addComponent(tfdStartDatum)
                                    .addComponent(tfdSlutDatum)
                                    .addComponent(tfdPrioritet)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdBeskrivning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdKostnad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(lblPartnersForProjekt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdAndraPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSparaAndringar)
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUppgifterOmProjekt)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartnersForProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdAndraPartners, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdProjektNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProjektNamn))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKostnader))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProjektbeskrivning)
                            .addComponent(tfdBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStartDatum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfdStartDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSlutDatum)
                            .addComponent(tfdSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatus)
                            .addComponent(tfdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHandlaggareforProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAndraHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLand)
                    .addComponent(btnSparaAndringar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAndraHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAndraHandlaggareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAndraHandlaggareActionPerformed

    private void tfdAndraPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdAndraPartnersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdAndraPartnersActionPerformed

    private void tfdKostnadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdKostnadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdKostnadActionPerformed

    private void tfdStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdStatusActionPerformed

    private void btnSparaAndringarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaAndringarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSparaAndringarActionPerformed

    private void btnSparaAndringarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSparaAndringarMouseClicked
        // TODO add your handling code here:
        
        String nyttProjektnamn = tfdProjektNamn.getText();
        String nyttKostnad = tfdKostnad.getText();
        String nyttBeskrivning = tfdBeskrivning.getText();
        String nyttStartDatum = tfdStartDatum.getText();
        String nyttSlutDatum = tfdSlutDatum.getText();
        String nyttStatus = tfdStatus.getText();
        String nyttPrioritet = tfdPrioritet.getText();
        
        //Uppdetara ändringar i databasen
        
        try {
            //Byta ändringar
            String updatesqlFraga = "UPDATE projekt SET " +  
                    "projektnamn = '" + nyttProjektnamn + "', " + 
                    "kostnad = '" + nyttKostnad + "'," +
                    "beskrivning = '" + nyttBeskrivning + "', " + 
                    "startdatum = '" + nyttStartDatum + "', " + 
                    "slutdatum = '" + nyttSlutDatum + "', " + 
                    "status ='" + nyttStatus + "'," +
                    "prioritet = '" + nyttPrioritet + "'" +
                    "WHERE projektchef = " + dbAid;
           
            System.out.println(updatesqlFraga);
            // Kör uppdateringen
            idb.update(updatesqlFraga);
            
            //Visa bekräftelse av ändringar
            JOptionPane.showMessageDialog(this, "Projektets Ändringar Är Sparade!");
        } catch (Exception e) {
            //Hantera fel?
            JOptionPane.showMessageDialog (this, "Fel vid inmatning av ändringar!" + e.getMessage());
        }
    }//GEN-LAST:event_btnSparaAndringarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyUppgifterOmProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyUppgifterOmProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyUppgifterOmProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyUppgifterOmProjektProjektledare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenyUppgifterOmProjektProjektledare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaAndringar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lblAndraHandlaggare;
    private javax.swing.JLabel lblHandlaggareforProjekt;
    private javax.swing.JLabel lblKostnader;
    private javax.swing.JLabel lblLand;
    private javax.swing.JLabel lblPartnersForProjekt;
    private javax.swing.JLabel lblProjektNamn;
    private javax.swing.JLabel lblProjektbeskrivning;
    private javax.swing.JLabel lblSlutDatum;
    private javax.swing.JLabel lblStartDatum;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblUppgifterOmProjekt;
    private javax.swing.JTextField tfdAndraPartners;
    private javax.swing.JTextField tfdBeskrivning;
    private javax.swing.JTextField tfdKostnad;
    private javax.swing.JTextField tfdPrioritet;
    private javax.swing.JTextField tfdProjektNamn;
    private javax.swing.JTextField tfdSlutDatum;
    private javax.swing.JTextField tfdStartDatum;
    private javax.swing.JTextField tfdStatus;
    // End of variables declaration//GEN-END:variables
}
