package projekt1;
import oru.inf.InfDB;
import javax.swing.JFrame;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.HashMap;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elsa
 */
public class MenyProfilHandlaggare extends javax.swing.JFrame {
     private InfDB idb; 
    private String dbAid;

    /**
     * Creates new form MenyProfilHandlaggare
     */
    public MenyProfilHandlaggare(InfDB idb, String dbAid) {
        this.idb = idb; 
        this.dbAid = dbAid;
        initComponents();
        
        
        fyllTextFalt ();
        FylliLabel ();
    
    }
    
    private void fyllTextFalt () {
        try{
            
       String query = "SELECT fornamn, efternamn, epost, telefon,losenord FROM anstalld where aid =" + dbAid;
        
       HashMap<String, String> userData = idb.fetchRow(query);
       
       if (userData != null) {
           tfdFornamn.setText (userData.get("fornamn"));
           tfdEfternamn.setText(userData.get("efternamn"));
           tfdEpost.setText (userData.get("epost"));
           tfdTelefon.setText(userData.get("telefon"));
           tfdLosenord.setText(userData.get("losenord"));
           
} else {JOptionPane.showMessageDialog (this, "Ingen data hittades om dig.");
       }
        
        }catch (InfException e) { 
    JOptionPane.showMessageDialog(this, "Fel vid hämtning av data!" + e.getMessage());
                    
       }
    }
    
    private void FylliLabel () {
        try{ 
            //Hämta data till label
            String query = "SELECT aid, avdelning, anstallningsdatum FROM anstalld where aid = " + dbAid;
            
            HashMap <String, String> userData = idb.fetchRow(query);
            
            if (userData != null) {
 
             lblAid.setText("Aid:" + userData.get("aid"));
             lblAvdelning.setText("Avdelning:" + userData.get("avdelning"));
             lblAnstallningsdatum.setText("Anställningsdatum:" +userData.get("anstallningsdatum"));
             } else { JOptionPane.showMessageDialog(this, "Ingen Data hittades om dig.");

            } 
            
} catch (InfException e) { 
    JOptionPane.showMessageDialog(this, "Fel vid hämtning av data!" + e.getMessage());
    
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdAndraTelefonnummer = new javax.swing.JTextField();
        lblMinProfil = new javax.swing.JLabel();
        lblMinaUppgifter = new javax.swing.JLabel();
        lblAid = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        lblAnstallningsdatum = new javax.swing.JLabel();
        lblMentor = new javax.swing.JLabel();
        tfdFornamn = new javax.swing.JTextField();
        tfdEfternamn = new javax.swing.JTextField();
        lblTelefonnummer = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        tfdEpost = new javax.swing.JTextField();
        tfdLosenord = new javax.swing.JTextField();
        tfdTelefon = new javax.swing.JTextField();
        btnSparaAndringar = new javax.swing.JButton();

        tfdAndraTelefonnummer.setText("Ändra Telefonnummer");
        tfdAndraTelefonnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdAndraTelefonnummerActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMinProfil.setText("Min profil ");

        lblMinaUppgifter.setText("Mina Uppgifter");

        lblAid.setText("Aid");

        lblAvdelning.setText("Avdelning");

        lblAnstallningsdatum.setText("Anstallningsdatum");

        lblMentor.setText("Mentor");

        tfdFornamn.setText("Förnamn");
        tfdFornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdFornamnActionPerformed(evt);
            }
        });

        tfdEfternamn.setText("Efternamn");

        lblTelefonnummer.setText("Telefon");

        lblLosenord.setText("Lösenord");

        lblFornamn.setText("Fornamn");

        lblEfternamn.setText("Efternamn");

        lblEpost.setText("Epost");

        tfdEpost.setText("Epost");

        tfdLosenord.setText("Lösenord");

        tfdTelefon.setText("Telefon");

        btnSparaAndringar.setText("Spara Ändringar");
        btnSparaAndringar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSparaAndringarMouseClicked(evt);
            }
        });
        btnSparaAndringar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaAndringarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblMinProfil)
                        .addGap(81, 81, 81)
                        .addComponent(lblMinaUppgifter)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAid)
                            .addComponent(lblAnstallningsdatum)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(tfdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblAvdelning)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFornamn)
                                    .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblEpost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLosenord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfdLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfdEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMentor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(btnSparaAndringar)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinProfil)
                    .addComponent(lblMinaUppgifter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornamn)
                    .addComponent(tfdFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfdEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(tfdLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonnummer))
                .addGap(9, 9, 9)
                .addComponent(lblAid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnstallningsdatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMentor)
                    .addComponent(btnSparaAndringar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdAndraTelefonnummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdAndraTelefonnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdAndraTelefonnummerActionPerformed

    private void tfdFornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdFornamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdFornamnActionPerformed

    private void btnSparaAndringarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaAndringarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSparaAndringarActionPerformed

    private void btnSparaAndringarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSparaAndringarMouseClicked
                //Hämta text från textfältet   
        String nyttFornamn = tfdFornamn.getText();
        String nyttEfternamn = tfdEfternamn.getText();
        String nyttEpost = tfdEpost.getText();
        String nyttTelefon = tfdTelefon.getText();
        String nyttLosenord = tfdLosenord.getText();
        
        //Uppdetara ändringar i databasen
        
        try {
            //Byta ändringar
            String updateQuery = "UPDATE anstalld SET " +  
                    "fornamn = '" + nyttFornamn + "', " + 
                    "efternamn = '" + nyttEfternamn + "'," +
                    "epost = '" + nyttEpost + "', " + 
                    "telefon = '" + nyttTelefon + "', " + 
                    "losenord = '" + nyttLosenord + "' " + 
                    "WHERE aid = " + dbAid;
            System.out.println(updateQuery);
             //Kör uppdateringen
            idb.update(updateQuery);
            
            //Visa bekräftelse av ändringar
            JOptionPane.showMessageDialog(this, "Dina Profil Ändringar Är Sparade!");
        } catch (Exception e) {
            //Hantera fel?
            JOptionPane.showMessageDialog (this, "Fel vid inmatning av ändringar!" + e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_btnSparaAndringarMouseClicked

     
                                                 
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyProfilHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyProfilHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyProfilHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyProfilHandlaggare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenyProfilHandlaggare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaAndringar;
    private javax.swing.JLabel lblAid;
    private javax.swing.JLabel lblAnstallningsdatum;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblMentor;
    private javax.swing.JLabel lblMinProfil;
    private javax.swing.JLabel lblMinaUppgifter;
    private javax.swing.JLabel lblTelefonnummer;
    private javax.swing.JTextField tfdAndraTelefonnummer;
    private javax.swing.JTextField tfdEfternamn;
    private javax.swing.JTextField tfdEpost;
    private javax.swing.JTextField tfdFornamn;
    private javax.swing.JTextField tfdLosenord;
    private javax.swing.JTextField tfdTelefon;
    // End of variables declaration//GEN-END:variables
}
