package projekt1;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author cecil
 */
public class MenyHallbarhetsmalHandlaggare extends javax.swing.JFrame{
    private InfDB idb; 
    private String dbAid;

    /**
     * Creates new form MenyHallbarhetsmalHandlaggare
     */
    public MenyHallbarhetsmalHandlaggare(InfDB idb, String dbAid) {
        this.idb = idb; 
        this.dbAid = dbAid; 
        initComponents();
        fyllComboBox(); //fyller rullistan med data från databasen
        
        //lägg till en lyssnare för att hantera val från rullistan
        boxNamn.addActionListener(evt -> {
        String valtMal = (String) boxNamn.getSelectedItem();//hämta valt namn
        if(valtMal!= null){
            uppdateraMalInfo(valtMal); //uppdatera målinformation
        }

       });
        
    }
    
    private void fyllComboBox() {
        try{
            String query ="SELECT namn FROM hallbarhetsmal";
            ArrayList<HashMap<String, String>> resultat = idb.fetchRows(query);
            
            if (resultat !=null) {
                boxNamn.removeAllItems();
                for (HashMap <String, String> rad : resultat) {
                boxNamn.addItem(rad.get("namn"));
                }
            }else{
                JOptionPane.showMessageDialog(this, "Inga hållbarhetsmål hittades i databasen.");
            }               
            } catch (InfException e) {
                JOptionPane.showMessageDialog(this, "Fel vid hämtning av hållbarhetsmål.");
        }
    }
    
    
    private void uppdateraMalInfo(String valtMal) {
        try {
            // Hämta målnummer och beskrivning från databasen baserat på valt namn
            String query = "SELECT malnummer, beskrivning FROM hallbarhetsmal WHERE namn = '" + valtMal + "'";
            HashMap<String, String> resultat = idb.fetchRow(query);
            
            if (resultat != null) {
                lblMalnummer.setText("Målnummer: " + resultat.get("malnummer"));
                tAreaBeskrivning.setText(resultat.get("beskrivning"));
            } else {
                lblMalnummer.setText("Målnummer: Ingen data");
                tAreaBeskrivning.setText("Ingen beskrivning tillgänglig.");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(this, "Fel vid hämtning av målinformation: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHallbarhetsmal = new javax.swing.JLabel();
        boxNamn = new javax.swing.JComboBox<>();
        lblMalnummer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAreaBeskrivning = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHallbarhetsmal.setText("Alla Hållbarhetsmål");

        boxNamn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMalnummer.setText("Malnummer");

        tAreaBeskrivning.setColumns(20);
        tAreaBeskrivning.setRows(5);
        jScrollPane2.setViewportView(tAreaBeskrivning);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHallbarhetsmal, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMalnummer))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHallbarhetsmal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMalnummer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                InfDB idb = new InfDB("databasensSökväg");
                new MenyHallbarhetsmalHandlaggare(idb, "1").setVisible(true);
            } catch (InfException e) {
                System.out.println("Fel vid anslutning till databasen: " + e.getMessage());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNamn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHallbarhetsmal;
    private javax.swing.JLabel lblMalnummer;
    private javax.swing.JTextArea tAreaBeskrivning;
    // End of variables declaration//GEN-END:variables

}
